#!/bin/sh
set -e

ARCH="${VIOLETIUM_ARCH:-amd64}"

case "$ARCH" in
    amd64|i386)
        BOOTLOADERS="grub-pc grub-efi"
        ;;
    arm64|armhf)
        BOOTLOADERS="grub-efi"
        ;;
    *)
        BOOTLOADERS=""
        KERNEL_FLAVOUR=""
        ;;
esac

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures "$ARCH" \
    --system live \
    --initramfs live-boot \
    --initsystem systemd \
    --bootappend-live "boot=live hostname=violetium" \
    --binary-image iso-hybrid \
    --bootloaders "$BOOTLOADERS" \
    --debian-installer live \
    --archive-areas "main contrib non-free non-free-firmware" \
    --firmware-binary true \
    --firmware-chroot true \
    --iso-application "VioletiumOS" \
    --iso-publisher "VioletiumOS Project" \
    --iso-volume "VIOLETIUM-$ARCH" \
    --image-name "VioletiumOS-$ARCH"

